;/*FB_PKG_DELIM*/

__d("ProdashCometV2ContentLibraryQuery$Parameters",["CometUFI_dedicated_comment_routable_dialog_gk.relayprovider","ContentLibraryStatusColumnGK.relayprovider","ContentLibraryUnifiedContentStatusGK.relayprovider","ProdashCometV2ContentLibraryQuery_facebookRelayOperation","enableProdashWebCrossPostInsights.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("ProdashCometV2ContentLibraryQuery_facebookRelayOperation"),metadata:{},name:"ProdashCometV2ContentLibraryQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__ContentLibraryStatusColumnGKrelayprovider:n("ContentLibraryStatusColumnGK.relayprovider"),__relay_internal__pv__CometUFI_dedicated_comment_routable_dialog_gkrelayprovider:n("CometUFI_dedicated_comment_routable_dialog_gk.relayprovider"),__relay_internal__pv__enableProdashWebCrossPostInsightsrelayprovider:n("enableProdashWebCrossPostInsights.relayprovider"),__relay_internal__pv__ContentLibraryUnifiedContentStatusGKrelayprovider:n("ContentLibraryUnifiedContentStatusGK.relayprovider")}}};a.exports=e}),null);
__d("ProdashManagePostsToolSortingTypes.facebook",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum").Mirrored(["METRICS_ASCENDING","METRICS_DESCENDING","MOST_COMMENTS","MOST_LIKES","MOST_RECENT","MOST_VIEWS"]),l=e;i.default=l}),66);
__d("ProfessionalDashboardInsightsContentMetricTypes.facebook",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum").Mirrored(["ADS_ON_REELS_EARNINGS","AVG_VIDEO_VIEW","COMMENTS","CREATOR_MONETIZATION_TOTAL_EARNINGS","DATE","DISTRIBUTION","ENGAGEMENT","IMPRESSIONS","INSTREAM_ADS_EARNINGS","INTERACTIONS","LIKES_SHARES_COMMENTS","NET_COMMENTS","NET_FOLLOW","NET_INTERACTION","PLAYS","RANKING_BY_VIEWS","REACH","REACTIONS","SAVES","SHARES","STARS_EARNINGS","TOTAL_EARNINGS","UNIFIED_PROGRAM_EARNINGS","VIDEO_VIEW","VIEWERS","VIEWS"]),l=e;i.default=l}),66);
__d("ProfessionalDashboardInsightsPlacementFilter.facebook",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum").Mirrored(["ALL","FEED","GROUPS"]),l=e;i.default=l}),66);
__d("XFBProdashYourPostsFilteringOptions.facebook",["$InternalEnum"],(function(t,n,r,o,a,i){var e=n("$InternalEnum").Mirrored(["ALL","DRAFT","GROUPS","PUBLISHED","SCHEDULED","UPLOADED"]),l=e;i.default=l}),66);
__d("ProdashCometV2ContentLibrary.entrypoint",["JSResourceForInteraction","ProdashCometV2ContentLibraryQuery$Parameters","buildProdashCometV2CompoundRoute.entrypoint","gkx"],(function(t,n,r,o,a,i,l){"use strict";var e="METRICS_DESCENDING",s="PUBLISHED",u="DATE",c="ALL",d=r("gkx")("12148"),m=d||r("gkx")("18548"),p=o("buildProdashCometV2CompoundRoute.entrypoint").buildProdashCometV2CompoundRouteEntrypoint(r("JSResourceForInteraction")("ProdashCometV2ContentLibrary.react").__setRef("ProdashCometV2ContentLibrary.entrypoint"),function(t){var r,o,a,i,l,d,p=t.routeProps;return{queries:{prodashCometV2ContentLibraryQueryReference:{parameters:n("ProdashCometV2ContentLibraryQuery$Parameters"),variables:{isExportEnabled:m,isMonetizationEnabled:(r=p.isMonetizationEnabled)!=null?r:!1,pageID:p.pageID,ref:p.ref,routeDateRange:p.date_range,routeEndDate:p.end_date,routeFilter:(o=p.filter)!=null?o:s,routeKeyword:p.keyword!=null?decodeURIComponent(p.keyword):null,routePlacementType:(a=p.placement_type)!=null?a:c,routePostType:p.post_type,routePostTypes:((i=p.post_types)==null?void 0:i.length)===1&&p.post_types[0]==="NONE"?[]:p.post_types,routeSortBy:(l=p.sort_by)!=null?l:u,routeSortingMethod:(d=p.sorting_method)!=null?d:e,routeStartDate:p.start_date,routeTranslationTypeFilter:p.translation_type_filter,shouldFetchOptimalTime:p.notifType==="applus_suggested_time_to_post"}}}}});l.default=p}),98);
__d("ProfileCometTimelineGridViewFeedQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26343548715326508"}),null);
__d("ProfileCometTimelineGridViewFeedQuery$Parameters",["GHLShouldChangeSponsoredDataFieldName.relayprovider","ProfileCometTimelineGridViewFeedQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("ProfileCometTimelineGridViewFeedQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometTimelineGridViewFeedQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__GHLShouldChangeSponsoredDataFieldNamerelayprovider:n("GHLShouldChangeSponsoredDataFieldName.relayprovider")}}};a.exports=e}),null);
__d("ProfileCometTimelineGridViewRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27214145651515961"}),null);
__d("ProfileCometTimelineGridViewRootQuery$Parameters",["ProfileCometTimelineGridViewRootQuery_facebookRelayOperation","WebPixelRatio.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("ProfileCometTimelineGridViewRootQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometTimelineGridViewRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__WebPixelRatiorelayprovider:n("WebPixelRatio.relayprovider")}}};a.exports=e}),null);
__d("ProfileCometTimelineGridViewRouteRoot.entrypoint",["JSResourceForInteraction","ProfileCometTimelineGridViewFeedQuery$Parameters","ProfileCometTimelineGridViewRootQuery$Parameters","WebPixelRatio","buildCometProfileRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildCometProfileRoute.entrypoint")(r("JSResourceForInteraction")("ProfileCometTimelineGridViewRoot.react").__setRef("ProfileCometTimelineGridViewRouteRoot.entrypoint"),function(e){var t={gridMediaWidth:230,omitPinnedPost:!0,privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"timeline",scale:o("WebPixelRatio").get(),userID:String(e.routeProps.userID)||""};return e.routeProps.hasMentionsTab===!0&&(t=babelHelpers.extends({},t,{postedBy:{group:"OWNER"}})),{queries:{timelineGridViewFeedQueryReference:{parameters:r("ProfileCometTimelineGridViewFeedQuery$Parameters"),variables:t},timelineGridViewRootQueryReference:{parameters:r("ProfileCometTimelineGridViewRootQuery$Parameters"),variables:{scale:o("WebPixelRatio").get(),userID:String(e.routeProps.userID)||""}}}}});l.default=e}),98);